"""Módulo que únicamente contiene la información sobre las canciones."""

canciones_clyde = [
    "MENSAJITO",
    "KitKat",
    "SEISNUEVE",
    "99/100 RMX",
    "YAILIN",
    "DAIQUIRI",
    "LA ÚLTIMA NOCHE",
    "COSTABLANCA",
    "TUMINI",
    "BUENISSSIMA",
    "BONNIE",
    "LA PIEDRA",
    "Jueves de Galería",
    "Enigma",
    "Cuando Perreamos",
    "3D",
    "Apartamento",
    "Código Secreto",
    "En la Playa",
    "El Santo",
    "Iguales",
    "La Vision RMX",
    "Tuenti RMX",
    "Colalé",
    "Tinieblas",
    "Tiendas",
    "seadoO",
    "BIEN :(",
    "Party Privado",
    "TU DÚO FAVORITO",
    "JOYYY",
    "VERANO - INVIERNO",
    "griselda",
    "DIESEL",
    "La Forma Q Me Miras",
    "Pobre Angelito RMX",
    "Mira RMX",
    "Sobrenatural",
    "Tuenti",
    "noche de sexoO",
    "CHERRY",
    "Vivienne",
    "BCN",
    "tu contactO",
    "BALMAIN",
    "amor de pobreE",
    "LOEWE",
    "SOLTERA49",
    "yasuni Pt.2",
    "10 DIASsS",
    "LAS TRAVIS",
    "La Vision",
    "LOS YINES",
    "yasuni",
    "GRACIAS DIOS",
    "PELoLISo",
    "miNENA49",
    "climax",
    "2014",
    "QSUCEDE?",
    "MMA",
    "papixulOo",
    "holaA:$",
    "LA CULPABLE",
    "Fantasia",
    "holaA:$ (extended version)",
    "adiosS(L)",
    "49",
    "Monty",
    "las estrellas",
    "el disco del ferxxO",
    "BART SIMPSON",
    "El Traje",
    "NOTAS DE VOZZZ",
    "EL MENUuU",
    "1DESEO",
    "Envuelto",
    "retros y perfumes",
    "solo x ig (2018)",
    "el arma",
    "xsiakaso:(",
    "LAS CONTRARIAS",
    "los mismos de antesS",
    "7VIDAS",
    "Tbt",
    "POBREDIABLA",
    "supernena",
    "AMNESIA",
    "LOS DE LA NUEVA ERA",
    "Haz Que Te Duele",
    "VOSE",
    "22",
    "sigo aqui freestyle (interludio)",
]


cantantes = {"Raul Clyde": canciones_clyde}
