lista_cantantes = [
    "Quevedo",
    "Bad Bunny",
    "Anuel AA",
    "Yung Beef",
    "Raul Clyde",
    "ladiferencia2006",
    "La Mafia del Amor",
    "Extremoduro",
    "JHAYCO",
    "Álvaro Díaz",
    "Aitana",
    "Alejo",
    "Lucho RK",
    "La Pantera",
    "Juseph",
    "SAIKO",
    "DELLAFUENTE",
    "Soge Culebra",
]
